apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
type: Opaque
data:
  transport-url: {{ .Values.transportUrl | b64enc | quote }}
  publisher-jwt-key: {{ .Values.publisherJwtKey | default (randAlphaNum 40) | b64enc | quote }}
  subscriber-jwt-key: {{ .Values.subscriberJwtKey | default (randAlphaNum 40) | b64enc | quote }}
  extra-directives: {{ .Values.extraDirectives | b64enc | quote }}
