version: "2"
run:
  tests: true
  build-tags:
    - deprecated_transport
    - deprecated_server
    - nobadger
    - nomysql
    - nopgx
linters:
  default: all
  settings:
    gomoddirectives:
      replace-local: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - generic
        - go.opentelemetry.io/otel/trace.Span
    spancheck:
      extra-start-span-signatures:
        - "github.com/dunglas/mercure.startSpan:opentelemetry"
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - forcetypeassert
    - gomodguard
    - intrange
    - lll
    - mnd
    - musttag
    - noinlineerr
    - nolintlint
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - gosec
          - funlen
          - gochecknoglobals
          - goconst
          - godox
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
