run:
  tests: true

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  enable-all: true
  disable:
    - errcheck
    - lll
    - wsl
    - gomnd
    - testpackage
    - exhaustruct
    - paralleltest
    - cyclop
    - forcetypeassert
    - tagliatelle
    - varnamelen
    - nonamedreturns

    # deprecated
    - interfacer
    - maligned
    - scopelint
    - golint
    - exhaustivestruct

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - funlen
        - godox
        - noctx
        - wrapcheck
