version: "2"
run:
  tests: true
linters:
  default: all
  disable:
    - canonicalheader
    - cyclop
    - depguard
    - errcheck
    - exhaustruct
    - forcetypeassert
    - intrange
    - lll
    - mnd
    - musttag
    - nolintlint
    - nonamedreturns
    - paralleltest
    - tagliatelle
    - testableexamples
    - testpackage
    - varnamelen
    - wsl
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - funlen
          - gochecknoglobals
          - goconst
          - godox
          - noctx
          - wrapcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
