---
run:
  tests: true

linters:
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  enable-all: true
  disable:
    - errcheck
    - lll
    - wsl
    - gomnd
    - testpackage
    - exhaustruct
    - paralleltest
    - cyclop
    - forcetypeassert
    - tagliatelle
    - varnamelen
    - nonamedreturns
    - testableexamples
    - musttag
    - depguard
    - mnd

    # weird issues
    - nolintlint
    - canonicalheader

    # deprecated
    - interfacer
    - maligned
    - scopelint
    - golint
    - exhaustivestruct
    - varcheck
    - ifshort
    - deadcode
    - nosnakecase
    - structcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gochecknoglobals
        - funlen
        - godox
        - noctx
        - wrapcheck
        - goconst
