before:
  hooks:
  - go mod download
builds:
- env:
  - CGO_ENABLED=0
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
  files:
  - COPYRIGHT
  - LICENSE
  - README.md
  - public/*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
dockers:
-
  image_templates:
  - 'dunglas/mercure:{{ .Tag }}'
  - 'dunglas/mercure:v{{ .Major }}'
  - 'dunglas/mercure:v{{ .Major }}.{{ .Minor }}'
  - 'dunglas/mercure:latest'
  extra_files:
  - public/
