version: 2
before:
  hooks:
    - go mod tidy
checksum:
  name_template: "checksums.txt"
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
release:
  prerelease: auto
  draft: true
env:
  - CGO_ENABLED=0

builds:
  - id: caddy
    dir: caddy/mercure
    ldflags:
      - -X 'github.com/caddyserver/caddy/v2.CustomVersion=Mercure.rocks {{ .Version }} Caddy'
    tags:
      - deprecated_transport
      - nobadger
      - nomysql
      - nopgx
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "5"
      - "6"
      - "7"
    ignore:
      - goos: windows
        goarch: arm

  - id: legacy
    dir: cmd/mercure
    ldflags:
      - -s -w -X github.com/dunglas/mercure/common.version={{ .Version }} -X github.com/dunglas/mercure/common.commit={{ .ShortCommit }} -X github.com/dunglas/mercure/common.buildDate={{ .Date }}
    tags:
      - deprecated_transport
      - deprecated_server
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    ignore:
      - goos: windows
        goarch: arm

upx:
  - enabled: true
    goos: [linux]
    compress: best

archives:
  - ids:
      - caddy
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - COPYRIGHT
      - LICENSE
      - README.md
      - Caddyfile
      - dev.Caddyfile
    format_overrides:
      - goos: windows
        formats: [zip]
  - id: legacy
    ids:
      - legacy
    name_template: >-
      {{ .ProjectName }}-legacy_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    files:
      - COPYRIGHT
      - LICENSE
      - README.md
    format_overrides:
      - goos: windows
        formats: [zip]

dockers_v2:
  - id: caddy
    ids:
      - caddy
    images:
      - "dunglas/mercure"
    tags:
      - "{{ .Tag }}"
      - "v{{ .Major }}"
      - "v{{ .Major }}.{{ .Minor }}"
      - "latest"
    platforms:
      - linux/amd64
      - linux/arm64/v8
    extra_files:
      - Caddyfile
      - dev.Caddyfile

  - id: legacy
    ids:
      - legacy
    dockerfile: Dockerfile.legacy
    images:
      - "dunglas/mercure"
    tags:
      - "legacy-{{ .Tag }}"
      - "legacy-v{{ .Major }}"
      - "legacy-v{{ .Major }}.{{ .Minor }}"
      - "legacy-latest"
    platforms:
      - linux/amd64
      - linux/arm64/v8

nfpms:
  - id: linux_packages
    package_name: mercure
    file_name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ with .Arm }}v{{ . }}{{ end }}.{{ .Format }}"
    ids:
      - caddy
    formats:
      - apk
      - deb
      - rpm
    maintainer: "Kévin Dunglas <kevin@dunglas.dev>"
    description: "An open, easy, fast, reliable and battery-efficient solution for real-time communications."
    license: "AGPL-3.0-or-later"
    vendor: "Dunglas Services SAS"
    homepage: "https://mercure.rocks"
    bindir: /usr/bin

signs:
  - artifacts: checksum
    args:
      [
        "--batch",
        "-u",
        "{{ .Env.GPG_FINGERPRINT }}",
        "--output",
        "${signature}",
        "--detach-sign",
        "${artifact}",
      ]
