language: go
go:
  - '1.14'

env:
  - GO111MODULE=on

services:
  - docker

before_install:
  - GO111MODULE=off go get github.com/mattn/goveralls
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin

install:
  - go get

script:
  - golangci-lint run ./...
  - CGO_ENABLED=0 GOOS=linux go build -v -a -ldflags '-extldflags "-static"' .
  - $GOPATH/bin/goveralls -race -service=travis-ci
after_success:
  - test -n "$TRAVIS_TAG" && docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux
