package mercure

import (
	"context"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"net/http"
	"strconv"
	"strings"

	"go.opentelemetry.io/otel/trace"
)

type updateContextKeyType struct{}

var UpdateContextKey updateContextKeyType //nolint:gochecknoglobals

// reservedTopicSubstring marks topics generated by the hub itself
// (e.g., subscription events). Publishers must not be able to forge
// those.
const reservedTopicSubstring = "/.well-known/mercure"

// Element-count caps prevent DoS amplification when callers fit many
// topics/matchers inside a request whose byte size is within transport
// limits (Caddy request_body, Go MaxHeaderBytes).
const (
	maxClaimMatchers = 1000 // mercure.subscribe / mercure.publish array
	maxQueryTopics   = 1000 // "topic" query params on subscribe
	maxPublishTopics = 1000 // "topic" form fields on publish
)

// Sentinel errors returned by Publish. Callers can branch on them via
// errors.Is.
var (
	ErrReservedTopic    = errors.New(`topic value references the reserved "/.well-known/mercure" namespace`)
	ErrInvalidEventID   = errors.New(`"id" field contains a forbidden control character`)
	ErrInvalidEventType = errors.New(`"type" field contains a forbidden control character`)
	ErrInvalidTopic     = errors.New("topic contains a forbidden control character or invalid UTF-8")
	ErrTooManyTopics    = errors.New("too many topics in update")
)

// sseFieldForbiddenChars, if copied into SSE id/event fields, would
// let a publisher inject arbitrary SSE fields into subscribers' streams.
const sseFieldForbiddenChars = "\x00\r\n"

// Validate enforces the publish-side input rules that protect subscribers
// from update forgery and SSE field injection. Hub.Publish calls it, so the
// bundled hub and PublishHandler are already covered.
//
// A caller that builds an Update from untrusted input (e.g. a publisher
// request) and dispatches it through a Transport directly, bypassing
// Hub.Publish, MUST call Validate first and reject the update on error.
// Skipping it lets a CR, LF, or NUL in ID or Type inject arbitrary SSE
// fields into subscribers' streams (CWE-93). Validate also rejects the
// reserved "/.well-known/mercure" topic namespace, so it is meant for
// publisher input, not hub-internal updates such as subscription events.
func (u *Update) Validate() error {
	topics := u.topics()
	if len(topics) > maxPublishTopics {
		return ErrTooManyTopics
	}

	for _, t := range topics {
		if strings.Contains(t, reservedTopicSubstring) {
			return fmt.Errorf("%q: %w", t, ErrReservedTopic)
		}

		// Control characters are forbidden by the protocol; a NUL would also
		// collide with the match cache's topic-list separator.
		if !validProtocolString(t) {
			return fmt.Errorf("%q: %w", t, ErrInvalidTopic)
		}
	}

	if strings.ContainsAny(u.ID, sseFieldForbiddenChars) {
		return ErrInvalidEventID
	}

	if strings.ContainsAny(u.Type, sseFieldForbiddenChars) {
		return ErrInvalidEventType
	}

	return nil
}

// Publish broadcasts the given update to all subscribers.
// The id field of the Update instance can be updated by the underlying Transport.
func (h *Hub) Publish(ctx context.Context, update *Update) error {
	ctx, span := startSpan(ctx, "mercure.publish", trace.WithSpanKind(trace.SpanKindProducer))
	// Deferred so the ID assigned by the transport via AssignUUID lands on the span.
	defer func() {
		if span.IsRecording() {
			span.SetAttributes(update.SpanAttributes()...)
		}

		span.End()
	}()

	if err := update.Validate(); err != nil {
		if h.logger.Enabled(ctx, slog.LevelInfo) {
			h.logger.LogAttrs(ctx, slog.LevelInfo, "Rejected invalid update", slog.Any("error", err))
		}

		recordSpanError(span, err)

		return err
	}

	ctx = context.WithValue(ctx, UpdateContextKey, update)

	if err := h.transport.Dispatch(ctx, update); err != nil {
		if h.logger.Enabled(ctx, slog.LevelError) {
			h.logger.LogAttrs(ctx, slog.LevelError, "Failed to dispatch update", slog.Any("error", err))
		}

		recordSpanError(span, err)

		return err //nolint:wrapcheck
	}

	h.metrics.UpdatePublished(update)

	if h.logger.Enabled(ctx, slog.LevelDebug) {
		h.logger.LogAttrs(ctx, slog.LevelDebug, "Update published")
	}

	return nil
}

// PublishHandler allows publisher to broadcast updates to all subscribers.
//
//nolint:funlen,gocognit
func (h *Hub) PublishHandler(w http.ResponseWriter, r *http.Request) {
	ctx, span := startSpan(r.Context(), "mercure.publish", trace.WithSpanKind(trace.SpanKindProducer))

	var u *Update
	// Deferred so the ID assigned by the transport via AssignUUID lands on the span.
	defer func() {
		if u != nil && span.IsRecording() {
			span.SetAttributes(u.SpanAttributes()...)
		}

		span.End()
	}()

	r = r.WithContext(ctx)

	var claims *claims

	if h.publisherJWTKeyFunc != nil {
		var err error

		claims, err = h.authorize(r, true)
		if err != nil || claims == nil {
			h.httpAuthorizationError(w, r, err)

			if err != nil {
				recordSpanError(span, err)
			}

			return
		}
	}

	if r.ParseForm() != nil { //nolint:gosec // body size can be limited using Caddy's request_body directive
		http.Error(w, http.StatusText(http.StatusBadRequest), http.StatusBadRequest)

		return
	}

	topics := r.PostForm["topic"]
	if len(topics) == 0 {
		http.Error(w, `Missing "topic" parameter`, http.StatusBadRequest)

		return
	}

	// The protocol allows exactly one topic per update; alternate topics are
	// a v8 feature, available only under the deprecated_topic build tag and
	// WithProtocolVersionCompatibility(8).
	if len(topics) > 1 && !h.allowsAlternateTopics() {
		http.Error(w, `Multiple "topic" parameters are not supported anymore, publish one update per topic`, http.StatusBadRequest)

		return
	}

	// Reject oversized topic lists before running canDispatch — otherwise
	// an authenticated publisher could force O(topics × selectors)
	// matching work on every request before being rejected by validate.
	if len(topics) > maxPublishTopics {
		http.Error(w, ErrTooManyTopics.Error(), http.StatusBadRequest)

		return
	}

	var retry uint64

	if retryString := r.PostForm.Get("retry"); retryString != "" {
		var err error
		if retry, err = strconv.ParseUint(retryString, 10, 64); err != nil {
			http.Error(w, `Invalid "retry" parameter`, http.StatusBadRequest)

			return
		}
	}

	private := len(r.PostForm["private"]) != 0
	if claims != nil && !claims.authz.grantsAll(h.topicSelectorStore, actionPublish, topics) { //nolint:nestif
		if private {
			http.Error(w, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)

			return
		}

		infoEnabled := h.logger.Enabled(ctx, slog.LevelInfo)
		if h.isBackwardCompatiblyEnabledWith(7) {
			if infoEnabled {
				h.logger.LogAttrs(ctx, slog.LevelInfo, `Deprecated: posting public updates to topics not listed in the "mercure.publish" JWT claim is deprecated since the version 7 of the protocol, use '["*"]' as value to allow publishing on all topics.`)
			}
		} else {
			if infoEnabled {
				h.logger.LogAttrs(ctx, slog.LevelInfo, `Unsupported: posting public updates to topics not listed in the "mercure.publish" JWT claim is not supported anymore, use '["*"]' as value to allow publishing on all topics or enable backward compatibility with the version 7 of the protocol.`)
			}

			http.Error(w, http.StatusText(http.StatusUnauthorized), http.StatusUnauthorized)

			return
		}
	}

	u = &Update{
		Private: private,
		Debug:   h.debug,
		Event:   Event{r.PostForm.Get("data"), r.PostForm.Get("id"), r.PostForm.Get("type"), retry},
	}
	u.setTopics(topics)

	dispatchCtx := context.WithoutCancel(ctx)

	// Validation, dispatch, logging and metrics live in Hub.Publish.
	if err := h.Publish(dispatchCtx, u); err != nil {
		switch {
		case errors.Is(err, ErrReservedTopic):
			http.Error(w, err.Error(), http.StatusForbidden)
		case errors.Is(err, ErrInvalidEventID), errors.Is(err, ErrInvalidEventType),
			errors.Is(err, ErrInvalidTopic), errors.Is(err, ErrTooManyTopics):
			http.Error(w, err.Error(), http.StatusBadRequest)
		default:
			http.Error(w, http.StatusText(http.StatusInternalServerError), http.StatusInternalServerError)
		}

		// Mirror the error onto the handler span too; Hub.Publish's child
		// span already records it, but leaving the parent span as success
		// is misleading.
		recordSpanError(span, err)

		return
	}

	if _, err := io.WriteString(w, u.ID); err != nil {
		if h.logger.Enabled(ctx, slog.LevelInfo) {
			h.logger.LogAttrs(ctx, slog.LevelInfo, "Failed to write publish response", slog.Any("error", err))
		}

		return
	}
}
