apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
data:
  debug: "{{ if .Values.debug }}debug{{ end }}"
  publisher-jwt-alg: {{ .Values.publisherJwtAlg | quote }}
  subscriber-jwt-alg: {{ .Values.subscriberJwtAlg | quote }}
