apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mercure.fullname" . }}
  labels:
    {{- include "mercure.labels" . | nindent 4 }}
data:
  global-options:  {{ .Values.globalOptions | quote }}
  publisher-jwt-alg: {{ .Values.publisherJwtAlg | quote }}
  subscriber-jwt-alg: {{ .Values.subscriberJwtAlg | quote }}
