# Default values for mercure.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# debug enables the debug mode
debug: false
# dev enables the development mode, including the debug UI and the demo
dev: false
# transportUrl is the URL representation of the transport to use
transportUrl: bolt:///data/mercure.db
# extraDirectives are extra Mercure directives to include in the Caddyfile
extraDirectives: ""

# publisherJwtKey is the JWT key to use for publishers, a random key will be generated if empty
publisherJwtKey: ""
# publisherJwtAlg the JWT algorithm to use for publishers
publisherJwtAlg: HS256

# subscriberJwtKey is the JWT key to use for subscribers, a random key will be generated if empty
subscriberJwtKey: ""
# subscriberJwtAlg the JWT algorithm to use for subscribers
subscriberJwtAlg: HS256

# license is your High Availability version license key (not necessary is you use the FOSS version): https://mercure.rocks/docs/hub/cluster
license: ""

# replicaCount is the number of replicas to create, this value must be 1 unless you are use the High Availability version: https://mercure.rocks/docs/hub/cluster
replicaCount: 1

image:
  repository: dunglas/mercure
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: mercure-example.local
      paths:
      - path: /
        backend:
          serviceName: mercure-example.local
          servicePort: 80
  tls: []
  #  - secretName: mercure-example-tls
  #    hosts:
  #      - mercure-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# autoscaling must not be enabled unless you are using the High Availability version: https://mercure.rocks/docs/hub/cluster
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
